### ISSUE TITLE
jQuery chain support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Illyism/jquery.vibrate.js#3]
Hi,

today I was trying to include your plugin and use it through jQuery.

The way you've done it is superawesome but it has a logical bug that breaks everything if the browser doesn't support Vibration API.

Practically on iOS and Safari for OSX my javascript is crashing because I cannot chain the call since you're not returning something. See this text example: http://jsbin.com/biqeruwume/1/

The affected line is this one, you're just returning something if Vibration API is there, while you should return always but do you stuff if you can do ( likely in your case, if you can use Vibration API ): https://github.com/Illyism/jquery.vibrate.js/blob/master/src/coffee/jquery.vibrate.coffee#L49

Thanks in advice!

**Comment by Illyism** [comment]
Good catch. I fixed it with the newest [version](https://github.com/Illyism/jquery.vibrate.js/commit/772f110052d509051ee67917211f02b50c5143fe).

**Comment by julianxhokaxhiu** [comment]
Thank you! :)
