### ISSUE TITLE
screen rubbish

### ISSUE THREAD

**Issue by scargill** [Illyism/jquery.vibrate.js#6]
I wonder if you can help..

I'm using the vibrate as such (simplified - so I have an image rollover and touch vibrate - works WONDERFULLY
```

<script src="/js/jquery.vibrate.min.js"></script>

<script>
$(".lightup").vibrate("short");

function restore_icon() {
        $(this).attr('src',$(this).attr('src').replace("_b.png",".png"));
    };

$('.lightup').on('mousedown', function() {
    $(this).attr('src',$(this).attr('src').replace(".png","_b.png"));  
    setTimeout(restore_icon.bind(this),500);
    });
</script>

<div layout="row" layout-align="space-between" style="padding:0px; text-align: left; margin:2px; border:2px solid black;">
<img class="lightup" src="http://www.scargill.net/icons/timed.png" ng-click="send({payload: 'p1dn' })" height="24px"/>
</div>
```

However... on a NON-mobile -  my text ends up totally garbled... some bracket info which should only display as "P1: 01:00  T1:16c" before the image... ends up like this..

{{"P1: "+ msg.payload.p1}} {{"T1: "+ msg.payload.t1 + "c"}}

In my example above how could I test to ensure this only happens in a mobile - or is there something else wrong - it absolutely works a treat on an android mobile..

**Comment by Illyism** [comment]
I think you're better off on using navigator.vibrate in your lightup-mousedown function. Just check if the feature is supported in the browser and then execute it.

**Comment by scargill** [comment]
All that effort and it turns out to be a single line of code :-)  Thank you for the advice. Tested, works.
